apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: vproappdata
  name: vproappdata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
