apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: vpromq01
  name: vpromq01
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vpromq01
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: vpromq01
    spec:
      containers:
        - env:
            - name: RABBITMQ_DEFAULT_PASS
              value: guest
            - name: RABBITMQ_DEFAULT_USER
              value: guest
          image: rabbitmq
          name: vpromq01
          ports:
            - containerPort: 15672
              protocol: TCP
      restartPolicy: Always
