apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: vproweb
  name: vproweb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vproweb
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: vproweb
    spec:
      containers:
        - image: vprocontainers/vprofileweb
          name: vproweb
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
