apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: vprodb
  name: vprodb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vprodb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: vprodb
    spec:
      containers:
        - env:
            - name: MYSQL_ROOT_PASSWORD
              value: vprodbpass
          image: vprocontainers/vprofiledb
          name: vprodb
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: vprodbdata
      restartPolicy: Always
      volumes:
        - name: vprodbdata
          persistentVolumeClaim:
            claimName: vprodbdata
